# Generated by Django 5.0.7 on 2024-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obituaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obituary',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
