# Generated by Django 5.0.7 on 2024-07-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obituaries', '0002_alter_obituary_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obituary',
            table='obituaries',
        ),
    ]
